name: skytropd
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.*
  - numpy >= 1.19
  - matplotlib
  - scipy >= 1.5
  - netCDF4
  - xarray
  - black
  - pytest
  - ipython
  - mypy
  - flake8
  - flake8-docstrings
  - jupyterlab
  - pooch
  - dask
  - pip
  - pip:
      - -e .
